version: '3'

services:
   
  mysqlDB:
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    deploy:
      placement:
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: "BOOKS"
      MYSQL_USER: "sudhi"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql

  api_gateway:
    image: "sudheksha/signin"
    container_name: gateway
    restart: always
    expose:
      - "8001"
    ports:
      - "8001:8001"
    deploy:
      placement:
    environment:
      DB_HOST: mysqlDB
      USER: sudhi
      PASSWORD: root
      DB: BOOKS


  add_products:
    image: "sudheksha/add_products"
    container_name: addProducts
    restart: always
    expose:
      - "8003"
    ports:
      - "8003:8003"
    deploy:
      placement:
    environment:
      DB_HOST: mysqlDB
      USER: sudhi
      PASSWORD: root
      DB: BOOKS


  get_products:
    image: "sudheksha/get_products"
    container_name: getProducts
    restart: always
    expose:
      - "8002"
    ports:
      - "8002:8002"
    deploy:
      placement:
    environment:
      DB_HOST: mysqlDB
      USER: sudhi
      PASSWORD: root
      DB: BOOKS

  order_products:
    image: "sudheksha/order_products"
    container_name: orderProducts
    restart: always
    environment:
      DB_HOST: mysqlDB
      USER: sudhi
      PASSWORD: root
      DB: BOOKS
    expose:
      - "8010"
    ports:
      - "8010:8010"
    deploy:
      placement:




