version: '3'

services:
   
  mysqlDB:
    image: mysql:latest
    container_name: myDB
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./../db.sql:/docker-entrypoint-initdb.d/init.sql


  api_gateway:
    image: "sudheksha/signin"
    container_name: gateway
    restart: always
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS


  add_products:
    image: "sudheksha/add_products"
    container_name: addProducts
    restart: always
    ports:
      - "8003:8003"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS


  get_products:
    image: "sudheksha/get_products"
    container_name: getProducts
    restart: always
    ports:
      - "8002:8002"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS

  order_products:
    image: "sudheksha/order_products"
    container_name: orderProducts
    restart: always
    ports:
      - "8010:8010"
    deploy:
      mode: replicated
      replicas: 1




