version: '3'

services:
   
  mysqlDB:
    image: mysql:latest
    container_name: myDB
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./../db.sql:/docker-entrypoint-initdb.d/init.sql


  api_gateway:
    build:
      context: ./../api_gateway
      dockerfile: ./../api_gateway/api_gateway.dockerfile
    container_name: gateway
    image: "sudheksha/signin"
    restart: always
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS


  add_products:
    build:
      context: ./../add_products
      dockerfile: ./../add_products/add_products.dockerfile
    container_name: addProducts
    restart: always
    ports:
      - "8003:8003"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS


  get_products:
    build:
      context: ./../get_products
      dockerfile: ./../get_products/get_products.dockerfile
    container_name: getProducts
    restart: always
    ports:
      - "8002:8002"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: myDB
      USER: root
      DB: BOOKS

  order_products:
    build:
      context: ./../order_products
      dockerfile: ./../order_products/order_products.dockerfile
    container_name: orderProducts
    restart: always
    ports:
      - "8010:8010"
    deploy:
      mode: replicated
      replicas: 1




